use std::sync::Arc;

use serde_json::Value;

use crate::context::ServerContext;
use crate::error::RpcServerError;

pub async fn server_definitions(
    _params: Value,
    _ctx: &Arc<ServerContext>,
) -> Result<Value, RpcServerError> {
    // Return protocol definitions statically.
    // These are the core XRPL type/field definitions used by clients.
    Ok(serde_json::json!({
        "TYPES": {
            "Done": -1,
            "Unknown": -2,
            "NotPresent": 0,
            "UInt16": 1,
            "UInt32": 2,
            "UInt64": 3,
            "Hash128": 4,
            "Hash256": 5,
            "Amount": 6,
            "Blob": 7,
            "AccountID": 8,
            "STObject": 14,
            "STArray": 15,
            "UInt8": 16,
            "Hash160": 17,
            "PathSet": 18,
            "Vector256": 19,
            "UInt192": 20,
            "UInt256": 21,
            "UInt384": 22,
            "UInt512": 23,
            "Issue": 24,
            "Transaction": 10001,
            "LedgerEntry": 10002,
            "Validation": 10003,
            "Metadata": 10004,
        },
        "TRANSACTION_TYPES": {
            "Payment": 0,
            "EscrowCreate": 1,
            "EscrowFinish": 2,
            "AccountSet": 3,
            "EscrowCancel": 4,
            "SetRegularKey": 5,
            "NickNameSet": 6,
            "OfferCreate": 7,
            "OfferCancel": 8,
            "SignerListSet": 12,
            "PaymentChannelCreate": 13,
            "PaymentChannelFund": 14,
            "PaymentChannelClaim": 15,
            "CheckCreate": 16,
            "CheckCash": 17,
            "CheckCancel": 18,
            "DepositPreauth": 19,
            "TrustSet": 20,
            "AccountDelete": 21,
            "SetHook": 22,
            "NFTokenMint": 25,
            "NFTokenBurn": 26,
            "NFTokenCreateOffer": 27,
            "NFTokenCancelOffer": 28,
            "NFTokenAcceptOffer": 29,
            "Clawback": 30,
            "AMMCreate": 35,
            "AMMDeposit": 36,
            "AMMWithdraw": 37,
            "AMMVote": 38,
            "AMMBid": 39,
            "AMMDelete": 40,
            "EnableAmendment": 100,
            "SetFee": 101,
            "UNLModify": 102,
            "BatchSubmit": 200,
        },
        "LEDGER_ENTRY_TYPES": {
            "AccountRoot": 97,
            "DirectoryNode": 100,
            "RippleState": 114,
            "Offer": 111,
            "LedgerHashes": 104,
            "Amendments": 102,
            "FeeSettings": 115,
            "Escrow": 117,
            "PayChannel": 120,
            "Check": 67,
            "DepositPreauth": 112,
            "NegativeUNL": 78,
            "NFTokenPage": 80,
            "NFTokenOffer": 55,
            "AMM": 121,
            "Bridge": 105,
            "DID": 73,
            "Oracle": 128,
            "Ticket": 84,
            "SignerList": 83,
        },
    }))
}
